spring.application.name=negozio-online

# spring.datasource.* serve per la configurazione della connessione al DB
spring.datasource.url=jdbc:mysql://localhost:3308/db_negozio_online
spring.datasource.username=root
spring.datasource.password=root

# Serve a controllare se le entita Java corrispondono alla struttura delle tabelle nel database
spring.jpa.hibernate.ddl-auto=update
# Fa stampare nella console le query SQL eseguite da Hibernate
# Hibernate e' un framework Java che si occupa di trasformare gli oggetti Java in righe di database e viceversa
spring.jpa.show-sql=true

# chiave segreta per firmare i JWT
jwt.secret=4Kx9vN7pQ2mL8sR5tY1wZ6cD3fH0jJ9nB7eT4uI2oP5aS8dF
# durata del token JWT in millisecondi (1 ora)
jwt.expiration=3600000
